# Base.
timezone: Europe/Madrid
markdown: kramdown
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - extras
plugins:
  - jekyll-sass-converter
  - jekyll-sitemap

# General.
name: 99languages
url: http://99languages.es
email: info@99languages.es
twitter: '@99languages'
phone: '+34881254499'
phone_formatted: '+34 881 254 499'
skype: info@99languages.es
google_site_verification: '7TihjyoEfiOZEI-MXyRF3_B9uK139bh6jbVgXVaZ8gg'
google_analytics: 'UA-115881613-1'

# Languages.
default_language: en
languages:
  en: English
  de: Deutsch
  es: Español
  gl: Galego

# SASS.
sass:
  style: :compressed
  sass_dir: _sass
