# Base.
timezone: Europe/Madrid
markdown: kramdown
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - extras
plugins:
  - jekyll-sass-converter
  - jekyll-sitemap

# General.
name: 99languages
url: http://99languages.es
email: info@99languages.es
twitter: '@99languages'
phone: '+34657278290'
phone_formatted: '+34 657 278 290'
skype: info@99languages.es
google_site_verification: ...
google_analytics: ...

# Languages.
default_language: en
languages:
  en: English
#  de: Deutsch
  es: Español
  gl: Galego

# SASS.
sass:
  style: :compressed
  sass_dir: _sass
